### ISSUE TITLE
composer.phar

### ISSUE THREAD

**Issue by JohnnyB3** [tigron/tiny-invoice#1]
i have a godaddy hosting pkg and can not use command line via telnet or other. so me running composer.phar is not an option.
seriously why are you using this when it limits the people that can use your project.
shame too as i was hoping to use it as it looked to have what i was looking for. oh well.

also to note you may want to place that in the install section as a requirement. and how to get/install.

**Comment by christopheg** [comment]
Hi Johnny,

You could do a git checkout on you local computer and run composer locally.
Next, just upload the complete directory via FTP.
That should work.

Kind regards,
Christophe
