### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by LionelLaffineur** [tigron/tiny-invoice#3]
Package jschaedl/iban is abandoned, you should avoid using it. Use jschaedl/iban-validation instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

**Comment by davidvandemaele** [comment]
The phpoffice/phpexcel package has been replaced by the phpoffice/phpspreadsheet package. 
For the jschaedl/iban package, I'm waiting for an issue I've opened.

**Comment by davidvandemaele** [comment]
The iban validation package is now in place.
